#!/bin/sh

adduser \
  --quiet \
  --system \
  --home /opt/payment \
  --no-create-home \
  --shell /bin/bash \
  --group \
  --gecos "Payment Service" \
  payment

systemctl daemon-reload
systemctl enable payment
systemctl start payment
